services:
  server:
    build:
      context: .
      dockerfile: websockets/Dockerfile.server
    networks:
        - transcendence
    environment:
      AI_WS_URL: "ws://server:8000"  # WebSocket via le nom du service 'server'

  ai_client:
    build:
      context: .
      dockerfile: PongAI/Dockerfile.ai
    depends_on:
      - server
    networks:
        - transcendence

  frontend_client:
    build:
      context: .
      dockerfile: ThreeJS_TEST/Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
        - transcendence
    environment:
      VITE_BACKEND_URL: "http://server:8000"
      VITE_WS_URL: "ws://server:8000"

networks:
  transcendence:
    driver: bridge