services:

  nginx:
    image: nginx:latest
    ports:
      - "81:81"  # Expose Nginx à l'hôte sur le port 81
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Monte ton fichier nginx.conf
    depends_on:
      - server
      - frontend_client
    networks:
      - transcendence

  server:
    build:
      context: .
      dockerfile: websockets/Dockerfile.server
    networks:
        - transcendence
    ports:
        - "8000:8000"
    environment:
      AI_WS_URL: "ws://server:8000"  # WebSocket via le nom du service 'server'

  ai_client:
    build:
      context: .
      dockerfile: PongAI/Dockerfile.ai
    depends_on:
      - server
    networks:
        - transcendence

  frontend_client:
    build:
      context: .
      dockerfile: ThreeJS_TEST/Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
        - transcendence
    environment:
      VITE_BACKEND_URL: "http://nginx:81"
      VITE_WS_URL: "ws://nginx:81"

networks:
  transcendence:
    driver: bridge